server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  application:
    name: dorandoran_backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3336/dorandoran_backend
    username: root
    password: 1234
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always